source 'https://rubygems.org'

gem "jekyll", "~> 3.9.2" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.3.3" # the latest release - currently 0.3.3
gem 'github-pages' # for GitHub Pages support

